### ISSUE TITLE
Generate the "Everything" modules directly?

### ISSUE THREAD

**Issue by ice1000** [agda/cubical#20]
I don't think they should be hand written. We can have a script for that purpose.

**Comment by mortberg** [comment]
This would be good to have for the `Basics` and `HITs` folders. In the `Core` folder I prefer to manage it myself because of name clashes and comments. 

I guess the best is if this script would be called from the Makefile before compiling the library? We should then also not track the Everything files in git.

**Comment by ice1000** [comment]
Yes. The Everything modules in the stdlib is generated, I think we can copy them directly and do some slight modification.

**Comment by mortberg** [comment]
Sounds good! Can you do it?

**Comment by mortberg** [comment]
An attempt to solve this was done in: https://github.com/agda/cubical/pull/26

See the discussion for why it wasn't merged. Contributions fixing it are welcome

**Comment by mortberg** [comment]
With https://github.com/agda/cubical/pull/243/files many of the Everything files won't re-export their content. These could be automatically generated.

**Comment by mortberg** [comment]
Solved via https://github.com/agda/cubical/pull/268. Thanks a lot @m-yac !
