### ISSUE TITLE
Maybe use GitHub actions for CI

### ISSUE THREAD

**Issue by phadej** [agda/cubical#222]
GitHub actions seems to have more powerful machines, and more time per job. I made a small proof-of-concept:
- cached build is quite fast: https://github.com/phadej/cubical/commit/b71c8e57ae33fd918d167755bd9fd704b91ddd9e/checks?check_suite_id=390942446
- non-cached agda build is slow, but still completes in "reasonable time": https://github.com/phadej/cubical/commit/42856d9e7b4b72d2c06fd2bdf5921b5d673a0280/checks?check_suite_id=390873409

The code is in https://github.com/phadej/cubical/commit/b71c8e57ae33fd918d167755bd9fd704b91ddd9e, it's quite straight forward, using `cabal v2-build` functionality. I'll be happy to walk through what happening it to whoever maintains `agda/cubical` CI setup

**Comment by Saizan** [comment]
Let's keep this as an option if travis starts acting up again.

**Comment by m-yac** [comment]
25 minutes of travis' roughly 28 minute runtime is just spent executing `cabal install`. It looks like the cached build above doesn't have this problem, I think we should switch to that.

It would be nice to get feedback about missed whitespace/compilation errors within a minute or two of updating a PR, instead of after nearly half an hour.

**Comment by m-yac** [comment]
That being said, I know nothing about CI so there are probably other factors to consider. I've just been frustrated with how slow travis is lately.

**Comment by Saizan** [comment]
@m-yac if you end up having to build Agda those are roughly the times even on a dedicated machine. The Github action linked above takes 38mins to install agda from scratch.

I guess whitespace checking could be made into a separate test and report results quicker?

By the way travis is just running `make test`, so you can also do that locally. You have to install `
fix-agda-whitespace` first though. See the `.travis.yml` file for how to.

**Comment by m-yac** [comment]
> @m-yac if you end up having to build Agda those are roughly the times even on a dedicated machine. The Github action linked above takes 38mins to install agda from scratch.

Hm, well I’m curious what the trouble  is with cached builds then. In fact, it looks [travis also supports cached builds](https://docs.travis-ci.com/user/caching/). Would keeping travis but caching the `.cabal` folder (e.g. like [here](https://github.com/haskell/cabal/blob/master/.travis.yml)) be viable? Maybe we could follow [this guide](https://docs.haskellstack.org/en/stable/travis_ci/), but substituting stack for cabal. That being said, the guide has a quote:

_For Stack on Travis to be practical, we must use caching. Otherwise build times will take an incredibly long time, about 30 minutes versus 3-5. Caching is currently available only for container-based Travis infrastructure._ 

Is our travis infrastructure container-based?

> I guess whitespace checking could be made into a separate test and report results quicker?

That sounds like a nice change regardless of the above!

**Comment by ayberkt** [comment]
Perhaps this can be of use for this issue: I have a Docker image set up with latest version of Agda, the standard library, and an older version of `cubical`: https://hub.docker.com/r/ayberkt/agda, which I use to continuously typecheck my developments and generate clickable HTML. It takes around three minutes in total (it typechecks `cubical` from scratch every time as well).

I use GitLab for this and I have no idea how to use GitHub actions but I'm guessing it should be quite easy to do the same thing.

**Comment by ayberkt** [comment]
I have built a GitHub action for Agda: https://github.com/ayberkt/agda-github-action. It takes around five minutes to typecheck my development and it should be the same for `cubical` as well. I will optimise this down to something like three minutes in the future. It seems to me that it is easier to use than Travis CI so you might at least consider using it for CI.

I have also set up automated deployment of clickable HTML using GitHub Pages with this. If you decide to switch to GitHub actions, it will hence be quite easy to address #17 using this.

**Comment by Saizan** [comment]
@ayberkt which version of Agda does it typecheck with?

Currently we are typechecking using the master branch of Agda.

**Comment by ayberkt** [comment]
@Saizan 

> @ayberkt which version of Agda does it typecheck with?

It typechecks using Agda 2.6.1 and it is using a Docker image in which this version of Agda is pre-installed. I was planning to keep the action up-to-date with the latest release of Agda, by updating the image every time a new release is made.

It did not occur to me, however, that one would like to use the development version of Agda for `cubical`. I suppose this will not be straightforward to do with the action as it is container-based.

Perhaps, what I can do is: I can make a new version of the Docker image in which Agda is installed from `master`. One can then tell the action to use the development version of Agda, in which case it would pull the newest updates and re-compile Agda, and I'm guessing this should still be significantly shorter than the current method? I can also automate this so that a new version of the image will be built nightly with the development of version Agda pre-compiled so this time should be minimised.

**Comment by Saizan** [comment]
The current travis script is caching (or supposed to cache) the build of Agda so it only takes the extra ~30 minutes to build if there's been a new commit.

I suppose it's not imperative that we follow agda/master in real-time like that, however it's fairly simpler than relying on an external docker image.

**Comment by ayberkt** [comment]
> however it's fairly simpler than relying on an external docker image

I do agree with that.

> The current travis script is caching (or supposed to cache) the build of Agda so it only takes the extra ~30 minutes to build if there's been a new commit.

I see. I checked the build a couple of times and it seemed like it always took ~30 minutes. I guess I happened to look at the non-cached cases.

In any case, maybe the GitHub action will be useful for something else in the future.

**Comment by mortberg** [comment]
I think Travis is working fine these days, so closing. Feel free to reopen if someone wants to discuss this more
