### ISSUE TITLE
Failing to build with latest Agda

### ISSUE THREAD

**Issue by dylanede** [agda/cubical#250]
I'm trying to use agda/cubical commit a42b953c1d896ae18b555d01c1619db38e7380b1 with agda/agda commit 6346ee71a0dcda824648894315619c994b3ebdf1. However when I try to use the cubical library, I get the following error:

```
~/cubical/Cubical/Foundations/GroupoidLaws.agda:115,1-7
There is no primitive function called prim^unglueU
when checking the definition of rUnitP
```

I'm using the following OPTIONS pragma:

```agda
{-# OPTIONS --cubical --safe --exact-split --without-K #-}
```

**Comment by m-yac** [comment]
This same error has appeared for me for a few months (i.e. on many previous builds of agda), but only when using emacs – command line compilation works fine. I figured it was a unique problem with my somewhat messed-up emacs installation, but I guess not.

**Comment by Saizan** [comment]
Thanks for the report! Our testing wasn't really gonna spot that.

The issue is that `Cubical.Foundations.GroupoidLaws` is not loading up `Agda.Builtin.Cubical.Glue` which contains the necessary primitives. (Strictly speaking it doesn't need `Glue`, but it needs `primFaceForall` in that module, plus the stuff in `.HCompU`)

We should add `Agda.Builtin.Cubical.Glue` to the stuff imported by `Cubical.Core.Primitives`.

**Comment by Saizan** [comment]
Oh, and the reason that it wasn't easy to spot is that if you first loaded some other file importing the necessary modules then the primitives/builtins are already loaded.

**Comment by m0rphism** [comment]
The same problem happened to me with the current master acabbd9595ad4291fd6f4bd2b1e802d285f676ed for file `Cubical.Foundations.Isomorphism`.

After adding `open import Cubical.Core.Glue` everything worked again.
