### ISSUE TITLE
Ring solver

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#297]
Would it be possible to hook the library up with a ring solver to avoid having to do tedious algebraic manipulations by hand? 

@oisdk : How much work would it be to do it for https://github.com/oisdk/agda-ring-solver ? 

(ping @felixwellen @borsiemir )

**Comment by oisdk** [comment]
It would probably be quite a bit of work.

* On the one hand, the solver was written --without-K, so theoretically the whole thing could be brought over.
* On the other, it heavily uses the standard library and standard library features, so I don't know how adaptable it is to the cubical library.
* The bulk of the code and trickiness in the faster solver is so that it can work with setoids, and so that it's fast. If you gave up those two things you could probably cut it down to a ~10th of the size.
* Also there's quite a bit of work going in to the reflection stuff, which isn't necessary to get a lot of the benefit from the solver.

It's also hard to guess what kind of difficulties you'd run into with inference for paths.

**Comment by felixwellen** [comment]
Do you have a minimal version we could try to port?

**Comment by oisdk** [comment]
While I don't have a minimal version of the ring solver, there are minimal versions of some of the components in the standard library.

* The reflection interface for the monoid solver I actually wrote as a minimal example of how to do reflection for this use case: [this file](https://github.com/agda/agda-stdlib/blob/master/src/Tactic/MonoidSolver.agda) has a full implementation of the reflection interface (with plenty of comments) on monoids.
* For the ring solver itself my thesis obviously has pretty in-depth explanations for everything, but I would also point you to the paper [Proving Equalities in a Commutative Ring Done Right in Coq](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.61.3041&rep=rep1&type=pdf). It has an excellent explanation of the "almost ring" algebra, and why it's needed.

Unfortunately I don't have time to work on this myself at the moment, but hopefully those two sources will help!

**Comment by felixwellen** [comment]
Thanks for the hints!

**Comment by felixwellen** [comment]
We now have a basic solver without a reflection interface. Examples are in Cubical/Algebra/RingSolver/CommRingExamples.agda for CommRings and in Cubical/Algebra/RingSolver/Examples.agda for Nat.

**Comment by felixwellen** [comment]
The ring solver for CommRings has a reflection interface now, so I would say this issue is fixed.

**Comment by Saizan** [comment]
Yep, got fixed by 7496bc4b659f9468d2123c8cd215da0b089f15a8
