### ISSUE TITLE
What to do about reverted PRs and compatibility with 2.6.2

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#703]
@L-TChen I just reverted two of your PRs:

https://github.com/agda/cubical/pull/701
https://github.com/agda/cubical/pull/702

as they broke compatibility with 2.6.2 which is the current version we're using to develop the library. I hope this won't cause any new problems with the CI.

Before merging any PRs that break compatibility with 2.6.2 we should discuss if we want to do this. I don't think we should do this as it's such a headache to make sure that everyone is using the same version of Agda and it's much easier if we're all just using the latest official release. Once 2.6.3 is out we can update the library

**Comment by L-TChen** [comment]
It is not just agda/cubical itself but also agda/agda is checking `cubical` as part of CI. So, if the library on the `master` is not compatible with the `master` branch of [agda/agda](https://github.com/agda/agda), the Agda's CI will break too. 

I can think of at least two possible "solutions"

1. Ignore `cubical` entirely during Agda's CI. 
2. Create an `experimental` branch like the standard library [agda-stdlib](https://github.com/agda/agda-stdlib) so that the `master` maintain the compatibility with `2.6.2` and the `experimental` branch accumulate commits compatible with the lastest commit, i.e. `2.6.3` but the stable release `2.6.2`.

**Comment by L-TChen** [comment]
> Agda developers with that problem just made an ad-hoc branch to reference from agda/master.

If Agda 2.6.3 has breaking changes which are not compatible with any commit on agda/cubical, then it won't work.

In this particular case, though, agda/cubical defines
https://github.com/agda/cubical/blob/1c56f5801ebdcb11563c180ada0d662525c75e7f/Cubical/Reflection/Base.agda#L49-L51
which is not used anywhere else. It is safe to remove this function so that the `agda/agda` on the master branch can still check `agda/cubical` without any issue. 

However, IMO it is wise to have a branch like `experimental` to check if the cubical library is compatible with the latest Agda.

**Comment by Saizan** [comment]
I meant an ad-hoc branch of agda/cubical, containing the commit that agda/master can reference.

But I guess let's agree to call that branch `experimental`, so that if there are multiple compatibility changes to make they are collected in one place, and `cubical` developers can merge it into `master` when the new Agda version releases.

We should probably write about this in `CONTRIBUTING.md`

**Comment by L-TChen** [comment]
Aha, I see. Thanks for the clarification.

> We should probably write about this in CONTRIBUTING.md

That will be nice. I looked for guidance in vain and every release of `agda/cubical` targets at a different version of Agda made me believe that the `master` branch is for the next release of Agda.

**Comment by xekoukou** [comment]
I too believed that the master branch was for the latest agda.

https://github.com/agda/cubical/blob/1c56f5801ebdcb11563c180ada0d662525c75e7f/INSTALL.md?plain=1#L4

**Comment by Saizan** [comment]
I think it's been for the latest agda for a while, but currently there are not as many cubical changes going on so the incentives are reversed.

**Comment by mortberg** [comment]
I agree that making changes that keeps the library compatible with both Agda master and the latest release is the best (so @L-TChen can feel free to comment or remove the code that causes problems). If this is not possible I think that having an experimental branch would be good.

As @xekoukou notes the documentation needs to be updated to reflect that the master branch of the library is now mainly intended to work on the latest release of Agda. I'm super busy these days, so can someone make a PR with this change before we forget?

**Comment by felixwellen** [comment]
#717 at least made changes to README and INSTALL, updating the phrase 'latest development version of Agda' with' to 'latest official release of Agda'. I guess there might still be other places that need some changing.

**Comment by mortberg** [comment]
Thanks! Closing this now
